~state_1_choose_weight = [[8, 2, 2].normalizeSum,[6, 6, 3].normalizeSum, [5, 5, 5].normalizeSum].scramble;


~trans_1_choose_weight = [[9, 1].normalizeSum,[1, 9].normalizeSum, [5, 5].normalizeSum].scramble;
~trans_2_choose_weight = [[9, 1].normalizeSum,[1, 9].normalizeSum, [5, 5].normalizeSum].scramble;
~trans_3_choose_weight = [[9, 1].normalizeSum,[1, 9].normalizeSum, [5, 5].normalizeSum].scramble;

