if(~playback_1_audio_test.value == 0, {~computer_state[\bomb].value}, {nil});
if(~playback_1_audio_test.value == 1, {~computer_state[\sporadic].value}, {nil});
if(~playback_1_audio_test.value == 2, {~computer_state[\poly].value}, {nil});
if(~playback_1_audio_test.value == 3, {~computer_state[\gran].value}, {nil});
if(~playback_1_audio_test.value == 4, {~computer_state[\pulse].value}, {nil});
if(~playback_1_audio_test.value == 5, {~computer_state[\tran].value}, {nil});
if(~playback_1_audio_test.value == 6, {~computer_state[\sparse].value}, {nil});


