if(~computer_routine_2_sample_1.isPlaying, {~computer_routine_2_sample_1.set(\gate, 0)}, {nil});
if(~computer_routine_2_sample_2.isPlaying, {~computer_routine_2_sample_2.set(\gate, 0)}, {nil});
if(~computer_routine_sub_sample.isPlaying, {~computer_routine_sub_sample.set(\gate, 0)}, {nil});
if(~computer_routine_2_sample_3.isPlaying, {~computer_routine_2_sample_3.set(\gate, 0)}, {nil});
if(~computer_routine_2_sample_4.isPlaying, {~computer_routine_2_sample_4.set(\gate, 0)}, {nil});
